name: CD

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  on-success:
    if: ${{ !contains(github.event.workflow_run.head_commit.message, 'No Deploy') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy Docker image to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_INSTANCE_IP }} << 'EOF'

          if ! command -v docker &> /dev/null
          then
            echo "Docker not found, installing Docker..."
            sudo apt-get update
            sudo apt-get install docker.io -y
            sudo systemctl start docker
            sudo usermod -aG docker $USER
          fi

          sudo docker container prune -y
          sudo docker image prune -a -y

          cat <<EOT > /home/ubuntu/config.py
          API_KEY = ${{ secrets.API_KEY }}
          EOT

          # Mount the config.py file into the container
          sudo docker run -d -p 80:80 -v /home/ubuntu/config.py:/app/config.py mohamadtr/streamlit-app:tagname

          EOF

          # Login to DockerHub on EC2
          echo "${{ secrets.DOCKER_TOKEN }}" | sudo docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
          
          sudo docker pull mohamadtr/streamlit-app:tagname

          # Stop any running containers
          sudo docker stop $(sudo docker ps -a -q) || true

          sudo docker run -d -p 80:80 mohamadtr/streamlit-app:tagname
