name: CD

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  on-success:
    if: ${{ !contains(github.event.workflow_run.head_commit.message, 'No Deploy') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy Docker image to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_INSTANCE_IP }} << 'EOF'
          sudo yum install docker -y
          docker pull mohamadtr/streamlit-app:tagname
          docker stop $(docker ps -a -q) || true
          docker run -d -p 80:80 mohamadtr/streamlit-app:tagname
          EOF 
